linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - staticcheck
    - typecheck
    - unused

  enable-all: false
  disable-all: true
  fast: false

issues:
  include:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
  exclude-dirs:
    - docs
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  build-tags:
    - integration
